name: laranja
channels:
- conda-forge
dependencies:
- python=3.9
- pip==22
- pip:
    - fastapi==0.85.0
    - uvicorn==0.18.2
    - black==22.6.0                 #dev
    - coverage==6.4.3               #dev
    - debugpy==1.6.2                #dev
    - flake8==5.0.2                 #dev
    - isort==5.10.1                 #dev
    - pre-commit==2.20              #dev
    - pylint==2.14.5                #dev
    - pytest==7.1.2                 #dev
